### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by mschauer** [mschauer/Bridge.jl#3]
- [x] Travis activated
- [x] Attobot activated
- [x] .travis.yml
- [x] LICENSE.md README.md REQUIRE
- [x] Tag Release

**Comment by mschauer** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10005

**Comment by tkelman** [comment]
There's quite a bit of type piracy (for the ones I found in a quick skim, see the Commit comments tab under https://github.com/mschauer/Bridge.jl/compare/faff7d50e88074ab90a274d2a5b37d67e96128a6...master#commit_comments_bucket) that it would be good to clean up. Either move method extension to the same package that defines a type, or Base (then Compat) where appropriate, or use a function name local to this package instead of extending from Base. Method extension has global side effects - it's safe to do so when either the method or at least one of the input types is from this package, but otherwise sketchy.
